/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HospitalFooter: typeof import('./src/components/layout/HospitalFooter.vue')['default']
    HospitalHeader: typeof import('./src/components/layout/HospitalHeader.vue')['default']
    HospitalLayout: typeof import('./src/components/layout/HospitalLayout.vue')['default']
    PatientFooter: typeof import('./src/components/layout/PatientFooter.vue')['default']
    PatientHeader: typeof import('./src/components/layout/PatientHeader.vue')['default']
    PatientLayout: typeof import('./src/components/layout/PatientLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
